---
# handlers file for activemq
 - name: restart activemq
   service:
     name:  "activemq"
     state: restarted
#   when: amq_service.changed == False

#  - name: reload systemd
#    sudo: yes
#    command: systemctl daemon-reload